volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

  production_redis_data: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: seaa_production_django
    volumes:
      - production_django_media:/app/seaa/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: seaa_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6

    volumes:
      - production_redis_data:/data


  celeryworker:
    <<: *django
    image: seaa_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: seaa_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: seaa_production_flower
    command: /start-flower
